Repository TwilioQuest/twilioquest-api-academy, pull requests merged in 2022-12, with the labels that each got.

#80 Added Objective Obstacle Functionality
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/maps/library.json
Labels: enhancement

#83 Added Inscription Fragments To Scrolls
  images/conversations/inscription-fragment.png
  levels/lovelace_tower/conversations/inscription-fragment-1.pug
  levels/lovelace_tower/conversations/inscription-fragment-2.pug
  levels/lovelace_tower/conversations/inscription-fragment-3.pug
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/library.json
Labels: enhancement

#87 Map script dec7
  images/conversations/inscription-fragment.png
  items/academy_jacket_neumann/index.json
  levels/house_ceremony/events.js
  levels/house_ceremony/maps/lovelacehallway.json
  levels/inside_perimeter/events.js
  levels/lovelace_tower/conversations/poster_lovelace.pug
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/maps/library.json
  scripts/helperFunctions.js
Labels: map, scripting

#55 Initial Commit For api-01-local-function Objective
  levels/lovelace_tower/level.json
  levels/lovelace_tower/objectives/api-01-local-function/description.md
  levels/lovelace_tower/objectives/api-01-local-function/example.js
  levels/lovelace_tower/objectives/api-01-local-function/objective.json
  levels/lovelace_tower/objectives/api-01-local-function/validator.js
  levels/lovelace_tower/objectives/api-01-local-function/walkthrough.md
Labels: objective

#57 Initial Commit For api-02-async-await Objective
  levels/lovelace_tower/level.json
  levels/lovelace_tower/objectives/api-02-async-await/description.md
  levels/lovelace_tower/objectives/api-02-async-await/example.js
  levels/lovelace_tower/objectives/api-02-async-await/houses/hopper.txt
  levels/lovelace_tower/objectives/api-02-async-await/houses/lovelace.txt
  levels/lovelace_tower/objectives/api-02-async-await/houses/neumann.txt
  levels/lovelace_tower/objectives/api-02-async-await/houses/turing.txt
  levels/lovelace_tower/objectives/api-02-async-await/objective.json
  levels/lovelace_tower/objectives/api-02-async-await/validator.js
  levels/lovelace_tower/objectives/api-02-async-await/walkthrough.md
Labels: objective

#60 Initial Commit For api-05-get-patch Objective
  levels/lovelace_tower/level.json
  levels/lovelace_tower/objectives/api-05-get-patch/description.md
  levels/lovelace_tower/objectives/api-05-get-patch/example.js
  levels/lovelace_tower/objectives/api-05-get-patch/objective.json
  levels/lovelace_tower/objectives/api-05-get-patch/validator.js
  levels/lovelace_tower/objectives/api-05-get-patch/walkthrough.md
Labels: objective

#59 Initial Commit For api-04-remote-and-local Objective
  levels/lovelace_tower/level.json
  levels/lovelace_tower/objectives/api-04-remote-and-local/description.md
  levels/lovelace_tower/objectives/api-04-remote-and-local/example.js
  levels/lovelace_tower/objectives/api-04-remote-and-local/objective.json
  levels/lovelace_tower/objectives/api-04-remote-and-local/validator.js
  levels/lovelace_tower/objectives/api-04-remote-and-local/walkthrough.md
Labels: objective

#86 Fix Player Exclamation Point Visibility For Catacombs Doorway After Opening Door
  levels/inside_perimeter/events.js
Labels: bug

#79 Added Automatic Door Opening/Closing Triggers and Functionality
  levels/house_ceremony/events.js
  scripts/handleTriggerDoors.js
Labels: enhancement

#90 Various updates and bug fixes
  levels/house_ceremony/events.js
  levels/house_ceremony/maps/lovelacehallway.json
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/maps/library.json
Labels: bug, enhancement

#91 Fixed handleTriggerDoors Bug
  scripts/handleTriggerDoors.js
Labels: bug

#92 Dec 9 updates
  levels/house_ceremony/conversations/sign.pug
  levels/house_ceremony/maps/courtyard.json
  levels/house_ceremony/maps/lovelacehallway.json
  levels/house_ceremony/maps/mainhall.json
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/maps/library.json
Labels: enhancement

#85 Added API Endpoints To Config
  scripts/config.js
Labels: enhancement

#93 Added Camera Pan To Academy Exterior
  levels/house_ceremony/events.js
  levels/house_ceremony/events/viewCourtyard.js
  levels/house_ceremony/maps/courtyard.json
Labels: enhancement

#94 Added Spell Animation
  levels/house_ceremony/maps/lovelacehallway.json
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/maps/library.json
  scripts/handleSpells.js
  scripts/useWand.js
Labels: bug, enhancement, scripting

#97 Release prep fixes and updates
  levels/inside_perimeter/events.js
  levels/inside_perimeter/maps/catacombs.json
  levels/inside_perimeter/maps/default.json
  levels/lovelace_tower/events.js
  levels/lovelace_tower/objectives/api-03-fetch/validator.js
  levels/lovelace_tower/objectives/api-04-remote-and-local/validator.js
  scripts/handleSpells.js
Labels: bug, enhancement

#98 Removed Misplaced Tile In Catacombs Map
  levels/inside_perimeter/maps/catacombs.json
Labels: bug

#103 Fixed Inside Perimeter Bramble Interactable Bug
  levels/inside_perimeter/events.js
  levels/inside_perimeter/objectives/neumann_key/validator.js
  package-lock.json
  package.json
  scripts/handleSpells.js
Labels: bug

#104 Various Updates And Bug Fixes
  levels/house_ceremony/conversations/lovelace-statue-corridor.pug
  levels/house_ceremony/maps/lovelacehallway.json
  levels/inside_perimeter/events.js
  levels/lovelace_tower/maps/library.json
  scripts/handleSpells.js
Labels: bug, enhancement

#106 Various updates and bug fixes
  levels/house_ceremony/maps/lovelacehallway.json
  levels/inside_perimeter/events.js
  levels/inside_perimeter/maps/catacombs.json
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/objectives/api-02-async-await/validator.js
  levels/lovelace_tower/objectives/api-03-fetch/description.md
  levels/lovelace_tower/objectives/api-03-fetch/walkthrough.md
  levels/lovelace_tower/objectives/api-04-remote-and-local/objective.json
  levels/lovelace_tower/objectives/api-05-get-patch/validator.js
Labels: bug, enhancement

#108 Milestone 1 aa3
  levels/house_ceremony/maps/lovelacehallway.json
  levels/inside_perimeter/events.js
  levels/inside_perimeter/maps/catacombs.json
  levels/lovelace_tower/events.js
  levels/lovelace_tower/maps/default.json
  levels/lovelace_tower/objectives/api-02-async-await/validator.js
  levels/lovelace_tower/objectives/api-03-fetch/description.md
  levels/lovelace_tower/objectives/api-03-fetch/walkthrough.md
  levels/lovelace_tower/objectives/api-04-remote-and-local/objective.json
  levels/lovelace_tower/objectives/api-05-get-patch/description.md
  levels/lovelace_tower/objectives/api-05-get-patch/validator.js
Labels: bug
